"""add_study_protocols_and_stage_sequence

Revision ID: 4bef16f0c354
Revises: 8aa3ae62ea35
Create Date: 2026-10-07 09:51:14.091125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bef16f0c354'
down_revision: Union[str, None] = '8aa3ae62ea35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_protocols',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ai_feedback_percentage', sa.Integer(), nullable=False),
    sa.Column('enabled_stages_json', sa.Text(), nullable=False),
    sa.Column('ptsot_config_json', sa.Text(), nullable=False),
    sa.Column('perspective_config_json', sa.Text(), nullable=False),
    sa.Column('lego_config_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sessions', sa.Column('stage_sequence_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'stage_sequence_json')
    op.drop_table('study_protocols')
    # ### end Alembic commands ###
